file:
  map: "/file/**"
  excel: "C:\\Users\\LvHao\\Desktop\\物联网项目\\excel"
  upload:
    path: "C:\\Users\\LvHao\\Desktop\\物联网项目\\file\\"
server:
  port: 8080
#ip: http://localhost:8085
ip: http://hzau.vipgz1.idcfengye.com